### ISSUE TITLE
TODO Stand 3.Dez

### ISSUE THREAD

**Issue by brn91** [brn91/FtwL#1]
-Das GameMenü und das Textinterface müssen noch angepasst werden für die späteren Wrapper-Klassen.
-Die Implementierung für einige Menüpunkte muss noch erstellt werden (zB. Der Punkt Beenden hat noch keine Funktion.
-Die Klassendiagramme müssen noch angepasst werden.
-Die Diagramme für die Abläufe könnten (wenn jemanden langweilig ist ;) )noch verfeinert werden. Zum Beispiel das Einfügen der Eingabesyntaxprüfung.
-Die ziehen() und schlagen() in den Klassen der Steine und der Lady sind noch experimentell, bzw noch nicht implementiert.

**Comment by Dan1194** [comment]
- individuelles Spielfeld erstellen (für Tester), damit Situationen getestet werden können.
-Projekordner vor src folder machen!
-Feldanalyse fertigstellen(richtige/falsche Züge erkennen, muss züge für computer etc).

**Comment by toadette77** [comment]
An die Programmierer:
Wir haben das Design von Humen vs Computer jetzt vorläufig fertig. Wichtig:
die ki hat jetzt eine methode macheZug(Field new Field(Spieler1.stones, Spieler2.stone) die  wiederum das veränderte Feld (beide Steinarrays zurückgeben geht ja leider nicht ) zurückgibt.
In dieser Methode soll dann alles intelligente passieren.
